### ISSUE TITLE
Big data analysis issues using the plugin

### ISSUE THREAD

**Issue by AdrianaCortes** [AlexHgO/Perseus_Plugin_Peptide_Collapse#12]
Hello,
Thank you very much for your software! 

I would appreciate it If you could help me with this question.
To sum up, I have performed a Phospho DIA analysis in 155 samples and used Spectronaut software resulting in a .txt 2GB weighted.
Previously I installed the Peptide Collapse plugin in Perseus_1.6.15.0  and it appears in the "External" menu in the "Processing" panel. 
Then, the matrix was well generated when I introduce the .txt (2GB) in the Perseus although I realized that the matrix had 5720000 rows.
However, when I performed the "Peptice Collapse", the software seemed to be frozen and no matrix is generated at any time. 
I consider that I have a potent analysis computer but I don`t know how to improve my process. Any advice would be thanked.

**Comment by AdrianaCortes** [comment]
After 2 hours frozen, Perseus has given me an error Saying:

Output
[1] "Care: Remove d 957762 rows not containin target PTM in EG.PTMLocalizationprobabilities"
[1] "Done: EG.PTMLocalizationprobabilitie s -based EG.PrecursorId correction and PTM position/probability extraction"
[1] "Done: site-level expansion"
[1] "Done: Long - to wide -format transformation"

Erro r
Warn ing message:
package ’data.tabIe’ was built under R version 4. 2 2 Warning message:
package ’doparalleI’ was built under R version 4. 2 2 Warning message:
package ’stringr’ was built under R version 4. 2 2 Warning message:
package ’MASS’ was built under R version 4. 2 2 Warning message:
package ’Bio c Man a ger’ was built under R version 4. 2 2 Warn ing message:
package ’GenomelnfoDb’ was built under R version 4. 2 2 Warning message:
package ’Verse us R’ was built under R version 4. 2 2 Erro r in h(simple Error(ms g, c all)) :
error in evaluating the argument ’X’ in selecting a method for function ’sapply’: object ’p G proteinGroups’ not found
Calls: [ .. eval - › s apply - › get - › get - › handIe Simple Error - › h Execution halted

**Comment by AlexHgO** [comment]
Hi Adriana,
Sorry for the delay, I am currently in the middle of a move.
From your error message, it seems like you tried to do site-level consolidation on protein-level, but no PG.ProteinGroups column is present in the report. Could this be? If so, then please try running the plugin with gene-level consolidation instead (assuming PG.Genes is included in the report).
I would also recommend running this test with just a sub-set of your data. If you can use R, simply keep only the first 100 rows of each MS run, and then run it with this 100x 155 rows reduced version to see if it crashes again.
If neither helps, I would need to have a look at the data. Could you make it available to me e.g. via cloud drive?

**Comment by AdrianaCortes** [comment]
Hi Alexander,


Thank you very much for your email. Your advice was very useful and,
finally, I made the Plugin work with my data. I performed a
Phosphosite configuration and got 35000 rows in my "collapsed" Perseus
file.
When I got the collapsed matrix, I saved and opened it in a different
Perseus file in order to reduce the complexity of my work. However,
this new file is so heavy I can not work with it properly even using a
potent computer. This is because, when I make my analysis with
Perseus, it triggers the generation of a massive amount of temporary
files I am not able to find. My files are so heavy due to I have 155
different samples in my study. Have you ever heard about this problem?
Any advice?

Thank you very much for your attention.
Best regards,
Adriana


[https://www.navarrabiomed.es/sites/default/files/files/docs/simbol-navarrabiomed.gif]  Adriana Cortés Jiménez
NAVARRABIOMED - CENTRO DE INVESTIGACIÓN BIOMÉDICA
INVESTIGADORA POSTDOCTORAL
UNIDAD DE NEUROPROTEÓMICA CLÍNICA
T +(34) 848 42 85 40 | ***@***.***>@***@***.***>
www.navarrabiomed.es<http://www.navarrabiomed.es/>
________________________________
De: Alexander Hogrebe ***@***.***>
Enviado: viernes, 2 de diciembre de 2022 16:46:54
Para: AlexHgO/Perseus_Plugin_Peptide_Collapse
Cc: Cortés Jiménez, Adriana (Biomed); Author
Asunto: Re: [AlexHgO/Perseus_Plugin_Peptide_Collapse] Big data analysis issues using the plugin (Issue #12)


Hi Adriana,
Sorry for the delay, I am currently in the middle of a move.
From your error message, it seems like you tried to do site-level consolidation on protein-level, but no PG.ProteinGroups column is present in the report. Could this be? If so, then please try running the plugin with gene-level consolidation instead (assuming PG.Genes is included in the report).
I would also recommend running this test with just a sub-set of your data. If you can use R, simply keep only the first 100 rows of each MS run, and then run it with this 100x 155 rows reduced version to see if it crashes again.
If neither helps, I would need to have a look at the data. Could you make it available to me e.g. via cloud drive?

**Comment by AlexHgO** [comment]
Hi Adriana,
I'm glad to hear you got it to work.
Could you elaborate what you mean by "so heavy" and "massive amount of temporary files"? Or could you share the generated matrix with me? Without further details it's difficult for me to tell what's going on. In general, exporting the matrix and then re-importing it into a fresh Perseus session sounds like the right approach to keep Perseus working and file sizes small.
Thanks and all the best,
Alexander
