### ISSUE TITLE
Plug-in doesn't work with Perseus 1.10.43 and 1.14.0

### ISSUE THREAD

**Issue by devang-mehta** [AlexHgO/Perseus_Plugin_Peptide_Collapse#3]
Hi, 
I can see the Plugin in the Externals dropdown on both these versions of Perseus, however, nothing happens when I click on the PeptideCollapse button. No window at all opens.

**Comment by AlexHgO** [comment]
Hi Devang,
Have you loaded a matrix into Perseus? The plugin will not open if no data is loaded.
Best, Alex
