### ISSUE TITLE
Fatal Error : You must specify '--save --no-save --vanilla'

### ISSUE THREAD

**Issue by hnolCol** [AlexHgO/Perseus_Plugin_Peptide_Collapse#4]
Hi Alexander, 

I am receiving this R fatal error message when trying to execute the plugin: 

<img width="379" alt="Error" src="https://user-images.githubusercontent.com/24191910/112834219-0350fc80-9098-11eb-96a8-8ee3df3b978a.png">

Tried with version: R.4.0.0 and R 3.6.3.

Is there a specific setting, I have to specify in R? 

Best wishes

Hendrik

**Comment by AlexHgO** [comment]
Hi Hendrik,

Sorry to hear about this. I've never seen this error, but let's try to get to the bottom of it.
Could you check which R version the plugin detects (under "Generic" -> "Executable")? When updating to new R versions, the previous instances often remain on the system, so the plugin might try to call upon an outdated R version. If this is the case, please try to uninstall all version of R, reinstall the newest one and then [re-execute the steps shown under "Installing R"](https://github.com/AlexHgO/Perseus_Plugin_Peptide_Collapse).

If this does not help, I tested the plugin (v1.4.2) on my system with the newest versions of R (R-4.0.4) and Perseus (1.6.15.0). Please download all these and then try to run the plugin with default settings on the "[example data](https://github.com/AlexHgO/Perseus_Plugin_Peptide_Collapse/tree/master/Example_data)" and let me know what happens.

Best, Alex

**Comment by hnolCol** [comment]
Hi Alex,

 please excuse the late reply. I believe it is actually a permission error since I do not have admin access on that particular computer. I believe that RServe (maybe used by the Perseus?) can cause this error.  I have not successfully used the plugin on a different computer. 

I will close the issue with this comment.
