### ISSUE TITLE
Perseus error

### ISSUE THREAD

**Issue by fazeliniah** [AlexHgO/Perseus_Plugin_Peptide_Collapse#5]
Hi Alex, 
I am using the newest version of Spectronaut to process phospho enriched DIA data. Unfortunately, I am getting the new error; please see the image. Do you have any thoughts? Appreciate your help in advance. 
Thanks

![peptide_collapse_error](https://user-images.githubusercontent.com/19155957/114066314-97c21880-9869-11eb-9898-bf2e030e0003.PNG)

**Comment by fazeliniah** [comment]
I figure out the issue. The PTM probability columns from Spectronaut were empty.

**Comment by fazeliniah** [comment]
I figured out the issue. The PTM probability columns from Spectronaut were empty.

**Comment by AlexHgO** [comment]
Great that you could figure it out, and thanks so much for letting me know!
