### ISSUE TITLE
Request for the new features.

### ISSUE THREAD

**Issue by andyzim111** [AlexHgO/Perseus_Plugin_Peptide_Collapse#7]
Thank the developer for this plugin.

If my files are not from Spectronaut, there is no PEP.peptideposition column.

But we have stripped peptide sequences in our results, and I think PEP.peptideposition can be obtained from stripped peptide sequences and fasta file. 

Could you add the function that PEP.peptideposition can be obtained from the peptide sequences and fasta to this tool?

Thanks a lot.

**Comment by AlexHgO** [comment]
You're welcome!
The plugin in its current form can process both Spectronaut and MaxQuant input data. Furthermore, MaxQuant and now also Spectronaut from version 15 on natively support site table export. I do not have plans to expand the plugin functionality to other input types anytime soon, but will consider it if I get to it. Thanks for the feedback!
